{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "32e31483",
   "metadata": {},
   "source": [
    "## Scrape the Houston NPR website\n",
    "\n",
    "https://www.houstonpublicmedia.org/\n",
    "\n",
    "I want a CSV file called `npr.csv` that includes a row for each story in the top section, with these columns:\n",
    "\n",
    "* `section`, the section of the story (e.g. \"Transportation\", \"Harris County\")\n",
    "* `title`, the title of the story\n",
    "* `url`, the full URL to the story\n",
    "\n",
    "If you want to start by printing these out, that's fine, but the end result is hopefully a CSV. If you'd like to filter out the rows without a title before saving that would be nice."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "018cc11b",
   "metadata": {},
   "outputs": [],
   "source": [
    "import requests\n",
    "from bs4 import BeautifulSoup\n",
    "\n",
    "response = requests.get(\"https://www.houstonpublicmedia.org/\")\n",
    "doc = BeautifulSoup(response.text)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "4f0b5517",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "36"
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "len(doc.find_all('article'))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "129a5111",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "32"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "len(doc.find_all(class_='post'))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "8bf69ced",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Abortion\n",
      "Supreme Court considers whether to reverse Roe v. Wade\n",
      "\n",
      "Nina Totenberg, NPRAt issue is whether to reverse the court's nearly half-century-old decision, Roe v. Wade, and subsequent decisions declaring that women have a constitutional right to terminate a pregnancy.\n",
      "Business\n",
      "There's a Santa shortage just weeks before Christmas\n",
      "\n",
      "Cory McGinnisA drop in supply to Santa Claus performers across the country has been attributed to some being at high risk for COVID-19.\n",
      "The Coronavirus\n",
      "Judge blocks Biden administration's COVID-19 vaccination mandate for health care workers after Texas, other states sue\n",
      "\n",
      "KAILYN RHONE, Texas TribuneTexas Attorney General Ken Paxton had called the mandate “an unprecedented federal vaccine decree” on health care workers.\n",
      "Criminal Justice\n",
      "Harris County will spend $2.6 million on a new policing program\n",
      "\n",
      "Kyra BuckleyThe Harris County Safe program aims to identify areas with high rates of violent crime, add police presence to those neighborhoods, and incorporate input from impacted communities.\n",
      "Education News\n",
      "Rice University has named a new director at the Kinder Institute for Urban Research\n",
      "\n",
      "Lucio VasquezRuth López Turley will officially take over after current director Bill Fulton steps down in June 2022.\n",
      "Weather\n",
      "2021 Atlantic hurricane season ends as third most active on record\n",
      "\n",
      "Sascha CordnerWith 21 named storms, this year’s Atlantic hurricane season was considered busy, but was not on par with the recording breaking 2020 hurricane season.\n",
      "Transportation\n",
      "TxDOT gets the OK to continue limited work on a controversial I-45 expansion\n",
      "\n",
      "Paul DeBenedetto / Gail DelaughterThe expansion was put on hold by the Federal Highway Administration in March over possible violations under Title VI of the 1964 Civil Rights Act.\n",
      "Harris County\n",
      "Harris County leaders create a new government board for low-wage frontline workers\n",
      "\n",
      "Lucio VasquezThe Harris County Essential Workers Board is the first of its kind in the U.S. to be comprised entirely of frontline workers.\n",
      "Houston Matters\n",
      "The 2022 job forecast for Houston (Dec. 1, 2021)\n",
      "\n",
      "Michael HagertyPending live coverage from the U.S. Supreme Court, Houston Matters will discuss the week in politics and get the job forecast for the region in 2022.\n",
      "Town Square\n",
      "'We are not done with the virus. And the virus is not done with us,' says global health expert about omicron\n",
      "\n",
      "Catherine LuExperts discuss the latest information on the omicron variant, as well as boosters and other COVID headlines.\n",
      "Breaking News\n",
      "Clear Brook High School is no longer under evacuation, after no bomb was found\n",
      "\n",
      "Matt HarabThe building was completely evacuated around 9:55 a.m., and law enforcement with bomb sniffing dogs were working as of 10:45 a.m. to investigate.\n",
      "Immigration\n",
      "Coronavirus shuts down legal proceedings in latest misstep for Texas border crackdown\n",
      "\n",
      "Jolie McCullough, Texas TribuneMigrants arrested under Gov. Greg Abbott’s border security push have been imprisoned for weeks or months waiting to appear before a judge. About 90 were finally to receive hearings this week, but court proceedings were canceled.\n",
      "Supreme Court considers whether to reverse Roe v. Wade argumentsAt issue is whether to reverse the court's nearly half-century-old decision, Roe v. Wade, and subsequent decisions declaring that women have a constitutional right to terminate a pregnancy.\n",
      "This Mississippi clinic is at the center of the case that could end Roe v. WadeA Mississippi case before the Supreme Court on Wednesday could result in a major rollback of abortion rights. The state has just one remaining clinic that offers abortions.\n",
      "Democracy is declining in the U.S. but it's not all bad news, a report findsThe United States has joined the list of countries where democracy is backsliding, according to a new report by the think tank International IDEA.\n",
      "CNN suspends Chris Cuomo indefinitely over his role in his brother's defense CNN said new documents \"raise serious questions\" about the anchor's role in trying to help his brother, former N.Y. governor Andrew Cuomo, respond to sexual misconduct allegations.\n",
      "Immigration\n",
      "'Misleading and dangerous' — Human rights groups condemn Gov. Abbott’s rhetoric on South Africa\n",
      "\n",
      "Pablo De La Rosa, Texas Public Radio\"The larger matter at hand here is that the Texas governor is trying to wind up fears around COVID and around this new strain of COVID to justify his anti-asylum and anti-migrant policies in South Texas,” said Ari Sawyer with Human Rights Watch.\n",
      "Military & Veterans' Issues\n",
      "Sutherland Springs victims’ lawyer calls government offer ‘inhumane, shocking’\n",
      "\n",
      "Paul Flahive, TPRIn his closing arguments, Attorney Jamal Alsaffar said the $31 million proposed by the federal government told him that it was “never interested in doing the right thing.”\n",
      "Houston Matters\n",
      "The omicron variant's threat to Houston (Nov. 30, 2021)\n",
      "\n",
      "Michael HagertyOn Tuesday's show: We find out what we know -- and what we don't -- about the omicron variant of COVID-19 and the threat it poses to Houston.\n",
      "Town Square\n",
      "What is the impact – and future – of Facebook and other digital technologies?\n",
      "\n",
      "Catherine LuToday, experts discuss the impact of social media, new digital technologies and digital activism. Plus, what do we know so far about the new omicron variant of the coronavirus?\n",
      "Health & Science\n",
      "Texas health experts 'not panicking' over COVID's omicron variant, expect cases to appear soon\n",
      "\n",
      "Bri Kirkham, TPRDoctors and health officials in Texas say the omicron variant of COVID-19 could be found in the state within the next couple of weeks -- if it’s not already here.\n",
      "astroworld\n",
      "14-year-old boy was trampled to death at Astroworld concert, family's attorney says\n",
      "\n",
      "William Menjivar, HPM InternThe suits alleges negligence and gross negligence on the part of all named defendants, including Apple, Travis Scott, Live Nation, and Scoremore.\n",
      "Health Matters\n",
      "Taking Care of a Caregiver\n",
      "\n",
      "Doug Mueller\"Caregivers need help to stay healthy.\"\n",
      "Bauer Business Focus\n",
      "Inclusive Designs\n",
      "\n",
      "Doug MuellerCompanies strive for inclusion and accessibility.\n",
      "Health & Science\n",
      "As omicron spreads, studies suggest that travel bans alone don't do much good\n",
      "\n",
      "DEEPA SHIVARAM, NPR / EMMA BOWMAN, NPR / Jaclyn Diaz, NPRPublic health experts warn that the rush to impose travel bans on southern African countries after the omicron variant was identified can work against scientific transparency.\n",
      "Election 2021\n",
      "Here are the 4 HISD board candidates facing a runoff\n",
      "\n",
      "Andrew SchneiderLocal, state, and national issues are all influencing the runoff elections for four seats on the Houston Independent School District Board of Trustees. Early voting begins today.\n",
      "Politics\n",
      "Matthew McConaughey says he won’t run for Texas governor\n",
      "\n",
      "Patrick Svitek, Texas TribuneThe actor said in a video Sunday that “political leadership” is a “path that I’m choosing not to take at this moment.”\n",
      "Houston Matters\n",
      "HISD board runoffs, and how Houston changed sports (Nov. 29, 2021)\n",
      "\n",
      "Michael HagertyOn Monday's show: We take a closer look at the runoff election for four seats on the HISD Board of Trustees, and a recent book examines how Houston and Texas helped change the sports landscape across the nation.\n",
      "Health & Science\n",
      "Health experts urge Texans to get vaccinated ahead of flu season\n",
      "\n",
      "Joseph Leahy, The Texas NewsroomThe Texas Medical Association is urging people to get flu shots due to concerns flu season could be worse this year with fewer people masking and crowds gathering again.\n",
      "Business\n",
      "A pandemic-fueled labor shortage has put a strain on some Houston restaurants\n",
      "\n",
      "William Menjivar, HPM InternAbout 78% of restaurant operators say they don't have enough staff to meet customer demand, according to the National Restaurant Association.\n",
      "Criminal Justice\n",
      "3 white men are found guilty of murder in the killing of Ahmaud Arbery\n",
      "\n",
      "Merrit Kennedy, NPR / Jaclyn Diaz, NPRThe jury reached its decision after more than 10 hours of deliberations following a trial in which prosecutors argued that the defendants provoked a confrontation with Arbery and defense attorneys said their clients were acting in self-defense.\n",
      "Houston Matters\n",
      "The week in politics, and the World Table Tennis Championships (Nov. 24, 2021)\n",
      "\n",
      "Michael HagertyOn Wednesday's show: We discuss the latest political news, and the World Table Tennis Championships come to Houston.\n",
      "Town Square\n",
      "How to avoid getting in the red when shopping on Black Friday\n",
      "\n",
      "Brenda ValdiviaExperts breakdown holiday spending from supply chain issues to the best Black Friday deals.\n",
      "Politics\n",
      "A Houston affordable housing program is now on hold, following a state review\n",
      "\n",
      "Jen RiceThe Texas General Land Office released the findings of its investigation into the city’s housing department, following ethics allegations against Mayor Sylvester Turner from the city's former housing director.\n",
      "Business\n",
      "Nearly 4 million Texans expected to travel this year for Thanksgiving holiday, AAA reports\n",
      "\n",
      "Sascha CordnerWhile the predicted travel volume in Texas is not expected to reach pre-pandemic levels, it’s close to what it was in 2019. That includes travel by car, plane, bus, train, and cruise ship.\n",
      "Politics\n",
      "U.S. Rep. Louie Gohmert joins Texas Republicans running against Attorney General Ken Paxton\n",
      "\n",
      "Patrick Svitek, Texas TribuneGohmert is at least the fourth GOP primary opponent that Paxton will face. At least three Democrats are also running for the job.\n"
     ]
    }
   ],
   "source": [
    "for story in doc.find_all('article'):\n",
    "    print(story.text.strip())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "39dc067a",
   "metadata": {},
   "outputs": [],
   "source": [
    "stories = doc.find_all(class_='post')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "7f0c5176",
   "metadata": {},
   "outputs": [],
   "source": [
    "stories = doc.select('.post')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "25dfe2de",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[{'section': 'Abortion',\n",
       "  'title': 'Supreme Court considers whether to reverse Roe v. Wade',\n",
       "  'url': 'https://www.houstonpublicmedia.org/articles/news/politics/2021/12/01/414481/supreme-court-considers-whether-to-reverse-roe-v-wade-in-historic-arguments/'},\n",
       " {'section': 'Business',\n",
       "  'title': \"There's a Santa shortage just weeks before Christmas\",\n",
       "  'url': 'https://www.houstonpublicmedia.org/articles/news/business/2021/12/01/414456/santa-shortage-hits-weeks-before-christmas/'},\n",
       " {'section': 'The Coronavirus',\n",
       "  'title': \"Judge blocks Biden administration's COVID-19 vaccination mandate for health care workers after Texas, other states sue\",\n",
       "  'url': 'https://www.houstonpublicmedia.org/articles/news/politics/2021/12/01/414470/judge-blocks-biden-administrations-covid-19-vaccination-mandate-for-health-care-workers-after-texas-other-states-sue/'},\n",
       " {'section': 'Criminal Justice',\n",
       "  'title': 'Harris County will spend $2.6 million on a new policing program',\n",
       "  'url': 'https://www.houstonpublicmedia.org/articles/news/criminal-justice/2021/12/01/414475/a-2-6-million-policing-proposal-will-increase-law-enforcement-presence-in-parts-of-unincorporated-harris-county/'},\n",
       " {'section': 'Education News',\n",
       "  'title': 'Rice University has named a new director at the Kinder Institute for Urban Research',\n",
       "  'url': 'https://www.houstonpublicmedia.org/articles/news/education-news/2021/12/01/414391/rice-university-names-next-director-of-kinder-institute-for-urban-research/'},\n",
       " {'section': 'Weather',\n",
       "  'title': '2021 Atlantic hurricane season ends as third most active on record',\n",
       "  'url': 'https://www.houstonpublicmedia.org/articles/news/weather/2021/12/01/414487/2021-atlantic-hurricane-season-ends-as-third-most-active-on-record/'},\n",
       " {'section': 'Transportation',\n",
       "  'title': 'TxDOT gets the OK to continue limited work on a controversial I-45 expansion',\n",
       "  'url': 'https://www.houstonpublicmedia.org/articles/news/transportation/2021/11/30/414398/txdot-gets-the-ok-to-continue-limited-work-on-a-controversial-i-45-expansion/'},\n",
       " {'section': 'Harris County',\n",
       "  'title': 'Harris County leaders create a new government board for low-wage frontline workers',\n",
       "  'url': 'https://www.houstonpublicmedia.org/articles/news/harris-county/2021/11/30/414399/harris-county-leaders-create-a-new-government-board-for-low-wage-frontline-workers/'},\n",
       " {'section': 'Houston Matters',\n",
       "  'title': 'The 2022 job forecast for Houston (Dec. 1, 2021)',\n",
       "  'url': 'https://www.houstonpublicmedia.org/articles/shows/houston-matters/2021/12/01/414440/the-2022-job-forecast-for-houston-dec-1-2021/'},\n",
       " {'section': 'Town Square',\n",
       "  'title': \"'We are not done with the virus. And the virus is not done with us,' says global health expert about omicron\",\n",
       "  'url': 'https://www.houstonpublicmedia.org/articles/shows/town-square/2021/11/30/414412/we-are-not-done-with-the-virus-and-the-virus-is-not-done-with-us-says-global-health-expert-about-omicron/'},\n",
       " {'section': 'Breaking News',\n",
       "  'title': 'Clear Brook High School is no longer under evacuation, after no bomb was found',\n",
       "  'url': 'https://www.houstonpublicmedia.org/articles/news/education-news/2021/11/30/414381/clear-brook-high-school-under-evacuation-after-potential-bomb-threat/'},\n",
       " {'section': 'Immigration',\n",
       "  'title': 'Coronavirus shuts down legal proceedings in latest misstep for Texas border crackdown',\n",
       "  'url': 'https://www.houstonpublicmedia.org/articles/news/politics/immigration/2021/11/30/414371/coronavirus-shuts-down-legal-proceedings-in-latest-misstep-for-texas-border-crackdown/'},\n",
       " {'section': 'Immigration',\n",
       "  'title': \"'Misleading and dangerous' — Human rights groups condemn Gov. Abbott’s rhetoric on South Africa\",\n",
       "  'url': 'https://www.houstonpublicmedia.org/articles/news/politics/immigration/2021/11/30/414365/misleading-and-dangerous-human-rights-groups-condemn-gov-abbotts-rhetoric-on-south-africa/'},\n",
       " {'section': \"Military & Veterans' Issues\",\n",
       "  'title': 'Sutherland Springs victims’ lawyer calls government offer ‘inhumane, shocking’',\n",
       "  'url': 'https://www.houstonpublicmedia.org/articles/news/criminal-justice/2021/11/30/414358/sutherland-springs-victims-lawyer-calls-government-offer-inhumane-shocking/'},\n",
       " {'section': 'Houston Matters',\n",
       "  'title': \"The omicron variant's threat to Houston (Nov. 30, 2021)\",\n",
       "  'url': 'https://www.houstonpublicmedia.org/articles/shows/houston-matters/2021/11/30/414295/the-omicron-variants-threat-to-houston-nov-30-2021/'},\n",
       " {'section': 'Town Square',\n",
       "  'title': 'What is the impact – and future – of Facebook and other digital technologies?',\n",
       "  'url': 'https://www.houstonpublicmedia.org/articles/shows/town-square/2021/11/29/414335/what-is-the-impact-and-future-of-facebook-and-other-digital-technologies/'},\n",
       " {'section': 'Health & Science',\n",
       "  'title': \"Texas health experts 'not panicking' over COVID's omicron variant, expect cases to appear soon\",\n",
       "  'url': 'https://www.houstonpublicmedia.org/articles/news/health-science/2021/11/29/414342/texas-health-experts-not-panicking-over-covids-omicron-variant-expect-cases-to-appear-soon/'},\n",
       " {'section': 'astroworld',\n",
       "  'title': \"14-year-old boy was trampled to death at Astroworld concert, family's attorney says\",\n",
       "  'url': 'https://www.houstonpublicmedia.org/articles/news/arts-culture-news/2021/11/29/414325/14-year-old-boy-was-trampled-to-death-at-astroworld-concert-familys-attorney-says/'},\n",
       " {'section': 'Health Matters',\n",
       "  'title': 'Taking Care of a Caregiver',\n",
       "  'url': 'https://www.houstonpublicmedia.org/articles/shows/health-matters/2021/11/29/414285/taking-care-of-a-caregiver/'},\n",
       " {'section': 'Bauer Business Focus',\n",
       "  'title': 'Inclusive Designs',\n",
       "  'url': 'https://www.houstonpublicmedia.org/articles/shows/bauer-business-focus/2021/11/29/414274/inclusive-designs/'},\n",
       " {'section': 'Health & Science',\n",
       "  'title': \"As omicron spreads, studies suggest that travel bans alone don't do much good\",\n",
       "  'url': 'https://www.houstonpublicmedia.org/articles/news/health-science/2021/11/29/414275/as-omicron-spreads-studies-suggest-that-travel-bans-alone-dont-do-much-good/'},\n",
       " {'section': 'Election 2021',\n",
       "  'title': 'Here are the 4 HISD board candidates facing a runoff',\n",
       "  'url': 'https://www.houstonpublicmedia.org/articles/news/in-depth/2021/11/29/414194/hisd-board-members-face-hard-runoff-challenges/'},\n",
       " {'section': 'Politics',\n",
       "  'title': 'Matthew McConaughey says he won’t run for Texas governor',\n",
       "  'url': 'https://www.houstonpublicmedia.org/articles/news/politics/2021/11/29/414267/matthew-mcconaughey-says-he-wont-run-for-texas-governor/'},\n",
       " {'section': 'Houston Matters',\n",
       "  'title': 'HISD board runoffs, and how Houston changed sports (Nov. 29, 2021)',\n",
       "  'url': 'https://www.houstonpublicmedia.org/articles/shows/houston-matters/2021/11/29/414118/hisd-board-runoffs-and-how-houston-changed-sports-nov-29-2021/'},\n",
       " {'section': 'Health & Science',\n",
       "  'title': 'Health experts urge Texans to get vaccinated ahead of flu season',\n",
       "  'url': 'https://www.houstonpublicmedia.org/articles/news/health-science/2021/11/24/414246/health-experts-urge-texans-to-get-vaccinated-ahead-of-flu-season/'},\n",
       " {'section': 'Business',\n",
       "  'title': 'A pandemic-fueled labor shortage has put a strain on some Houston restaurants',\n",
       "  'url': 'https://www.houstonpublicmedia.org/articles/news/in-depth/2021/11/24/414025/a-pandemic-fueled-labor-shortage-has-put-a-strain-on-some-houston-restaurants/'},\n",
       " {'section': 'Criminal Justice',\n",
       "  'title': '3 white men are found guilty of murder in the killing of Ahmaud Arbery',\n",
       "  'url': 'https://www.houstonpublicmedia.org/articles/news/criminal-justice/2021/11/24/414220/all-3-defendants-found-guilty-of-murdering-ahmaud-arbery/'},\n",
       " {'section': 'Houston Matters',\n",
       "  'title': 'The week in politics, and the World Table Tennis Championships (Nov. 24, 2021)',\n",
       "  'url': 'https://www.houstonpublicmedia.org/articles/shows/houston-matters/2021/11/24/414108/the-week-in-politics-and-the-world-table-tennis-championships-nov-24-2021/'},\n",
       " {'section': 'Town Square',\n",
       "  'title': 'How to avoid getting in the red when shopping on Black Friday',\n",
       "  'url': 'https://www.houstonpublicmedia.org/articles/shows/town-square/2021/11/23/414166/how-to-avoid-getting-in-the-red-when-shopping-on-black-friday/'},\n",
       " {'section': 'Politics',\n",
       "  'title': 'A Houston affordable housing program is now on hold, following a state review',\n",
       "  'url': 'https://www.houstonpublicmedia.org/articles/news/politics/2021/11/23/414165/houstons-affordable-housing-program-is-now-on-hold-following-a-state-review/'},\n",
       " {'section': 'Business',\n",
       "  'title': 'Nearly 4 million Texans expected to travel this year for Thanksgiving holiday, AAA reports',\n",
       "  'url': 'https://www.houstonpublicmedia.org/articles/news/business/2021/11/23/414125/nearly-4-million-texans-expected-to-travel-this-year-for-thanksgiving-holiday-aaa-reports/'},\n",
       " {'section': 'Politics',\n",
       "  'title': 'U.S. Rep. Louie Gohmert joins Texas Republicans running against Attorney General Ken Paxton',\n",
       "  'url': 'https://www.houstonpublicmedia.org/articles/news/politics/2021/11/23/414100/u-s-rep-louie-gohmert-joins-texas-republicans-running-against-attorney-general-ken-paxton/'}]"
      ]
     },
     "execution_count": 18,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "dataset = []\n",
    "for story in stories:\n",
    "    data = {}\n",
    "    data['section'] = story.find('h3').text\n",
    "    data['title'] = story.find('h2').text\n",
    "    data['url'] = story.find('a')['href']\n",
    "    dataset.append(data)\n",
    "dataset"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "6814a223",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>section</th>\n",
       "      <th>title</th>\n",
       "      <th>url</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Abortion</td>\n",
       "      <td>Supreme Court considers whether to reverse Roe...</td>\n",
       "      <td>https://www.houstonpublicmedia.org/articles/ne...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Business</td>\n",
       "      <td>There's a Santa shortage just weeks before Chr...</td>\n",
       "      <td>https://www.houstonpublicmedia.org/articles/ne...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>The Coronavirus</td>\n",
       "      <td>Judge blocks Biden administration's COVID-19 v...</td>\n",
       "      <td>https://www.houstonpublicmedia.org/articles/ne...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Criminal Justice</td>\n",
       "      <td>Harris County will spend $2.6 million on a new...</td>\n",
       "      <td>https://www.houstonpublicmedia.org/articles/ne...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Education News</td>\n",
       "      <td>Rice University has named a new director at th...</td>\n",
       "      <td>https://www.houstonpublicmedia.org/articles/ne...</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "            section                                              title  \\\n",
       "0          Abortion  Supreme Court considers whether to reverse Roe...   \n",
       "1          Business  There's a Santa shortage just weeks before Chr...   \n",
       "2   The Coronavirus  Judge blocks Biden administration's COVID-19 v...   \n",
       "3  Criminal Justice  Harris County will spend $2.6 million on a new...   \n",
       "4    Education News  Rice University has named a new director at th...   \n",
       "\n",
       "                                                 url  \n",
       "0  https://www.houstonpublicmedia.org/articles/ne...  \n",
       "1  https://www.houstonpublicmedia.org/articles/ne...  \n",
       "2  https://www.houstonpublicmedia.org/articles/ne...  \n",
       "3  https://www.houstonpublicmedia.org/articles/ne...  \n",
       "4  https://www.houstonpublicmedia.org/articles/ne...  "
      ]
     },
     "execution_count": 20,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import pandas as pd\n",
    "\n",
    "df = pd.DataFrame(dataset)\n",
    "df.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "e07b1fda",
   "metadata": {},
   "outputs": [],
   "source": [
    "df.to_csv(\"npr.csv\", index=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": "null",
   "id": "bd8cbf20",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
